name: .NET Core CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0' 

      - name: Restore dependencies
        run: |
          dotnet restore Lab1/Lab1.csproj  # Вказати шлях до вашого основного проекту
          dotnet restore Lab2/Lab2.csproj  # Додайте інші лабораторні проекти тут
          dotnet restore Lab1.Tests/Lab1.Tests.csproj  # Додайте тести для Lab1
          dotnet restore Lab2.Tests/Lab2.Tests.csproj  # Додайте тести для Lab2

      - name: List files
        run: ls -R  # Переглянути всі файли і каталоги

      - name: Build and Test projects
        run: |
          dotnet build build.proj -p:Solution=Lab1 -t:Test
          dotnet build build.proj -p:Solution=Lab2 -t:Test

      - name: Run tests
        run: |
          dotnet test Lab1.Tests/Lab1.Tests.csproj --configuration Release --no-build --verbosity normal
          dotnet test Lab2.Tests/Lab2.Tests.csproj --configuration Release --no-build --verbosity normal
