name: .NET Core CI

on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0' 
          
      - name: Check .NET version
        run: dotnet --version

      - name: Restore dependencies
        run: |
          dotnet restore Lab1/Lab1.csproj
          dotnet restore Lab2/Lab2.csproj
          dotnet restore Lab3/Lab3.csproj
          dotnet restore Lab1.Tests/Lab1.Tests.csproj
          dotnet restore Lab2.Tests/Lab2.Tests.csproj
          dotnet restore Lab3.Tests/Lab3.Tests.csproj

      - name: List files
        run: ls -R  # Переглянути всі файли
        
      - name: Run Lab1
        run: |
          dotnet build build.proj -p:Solution=Lab1 -t:Run

      - name: Run Lab2
        run: |
          dotnet build build.proj -p:Solution=Lab2 -t:Run
          
          
      - name: Test Lab1
        run: |
          dotnet build build.proj -p:Solution=Lab1 -t:Test
      
      - name: Test Lab2
        run: |
          dotnet build build.proj -p:Solution=Lab2 -t:Test
          
      - name: Test Lab3
        run: |
          dotnet build build.proj -p:Solution=Lab3 -t:Test

